[package]
name = "AutomaSploitService"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11.6"
actix-web = { version = "4.9.0", features = ["default"] }
serde = { version = "1.0.217", features = ["derive"] }